### ISSUE TITLE
Support serving ANS-102 data items from data route

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/gateway#24]
### Description

- Currently, the gateway parses and indexes ANS-102 bundles which allow them to be queried through the GraphQL API.

- However, the gateway doesn't store the data of these data items for serving to clients.

- The gateway needs to store data item data as they cannot be retrieved from miners efficiently. (possibly compressed in some way)

- The gateway should store and serve up data item data to clients.

**Comment by TheLoneRonin** [comment]
> The gateway needs to store data item data as they cannot be retrieved from miners efficiently. (possibly compressed in some way)

This is something I need to account for too! Thanks, will close my other issue.

**Comment by TheLoneRonin** [comment]
Resolved in v1.0.0
