### ISSUE TITLE
Support streaming download of transaction data

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/gateway#5]
From the implementation [here](https://github.com/ArweaveTeam/gateway/blob/3b8797c58bcd77878be5ad8d3011262b5ea8b65b/src/route/data.route.ts#L10) it looks like transaction data is entirely buffered into memory first before being sent to the client.

Ideally, it should be streamed in straight to the client to reduce latency and to allow loading of transactions larger than the ~2GB Node supports.

**Comment by samcamwilliams** [comment]
If you can build it, this would be great! It is a nice feature, but hasn't been a priority so far.
