### ISSUE TITLE
Possible need for sanitization

### ISSUE THREAD

**Issue by zcstarr** [ArweaveTeam/gateway#50]
In theory someone could have a path that is "drop db". Just putting this up here for reference.

https://github.com/ArweaveTeam/gateway/blob/285585c1e563b21be5c5ae0bc6e9c9d61282f725/src/database/import.database.ts#L9

**Comment by samcamwilliams** [comment]
This is only called by the gateway operator, on data that they already trust, right?

**Comment by TheLoneRonin** [comment]
@samcamwilliams yup that's an absolute path based on `.env`.

**Comment by TheLoneRonin** [comment]
@zcstarr, in general, we should be sanitizing all raw inputs. Even though the path is based on `.env` for good measure escaping and sanitizing it is a good idea! :)

**Comment by TheLoneRonin** [comment]
function not exposed to public queries.
