### ISSUE TITLE
Support custom filters for transactions to be indexed

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/gateway#6]
To reduce database storage requirements, I would like to be able to choose which transactions I want to index in the database based on various attributes such as tags, owner, and the recipient (for AR transfers).

Considering how complex the filtering logic could be I wonder what kind of format it should be defined in. Perhaps allow a custom JS function to be defined in some kind of config script? Assuming this will be a common use case for developers, it would be ideal not to need to fork the repo to implement our own filters.

**Comment by samcamwilliams** [comment]
Yep -- very nice.

On the node itself you can write a custom Erlang handler. Mirroring that on the gateway would make a lot of sense.
