### ISSUE TITLE
Support transaction creation/upload and seeding

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/gateway#8]
The `arweave.net` gateway supports creating and uploading transactions. It additionally seeds uploaded chunks to its peers to ensure that data is not lost in the event of a node failure.

This gateway currently doesn't support that.

**Comment by samcamwilliams** [comment]
> The arweave.net gateway supports creating and uploading transactions

Please can you provide more detail on the API you are referring to?

> It additionally seeds uploaded chunks to its peers to ensure that data is not lost in the event of a node failure.

@TheLoneRonin -- what is the situation regarding chunk seeding with this branch? We should indeed be seeding chunks to at least the trusted peers.

**Comment by CDDelta** [comment]
> Please can you provide more detail on the API you are referring to?
I was simply referring to the [Arweave HTTP API](https://docs.arweave.org/developers/server/http-api#submit-a-transaction), not the GraphQL API 😄

**Comment by samcamwilliams** [comment]
Ah -- posting a well-formed, signed TX? Yes, we should definitely be supporting that in this version.
