### ISSUE TITLE
Support wallet balance retrieval

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/gateway#9]
The Arweave HTTP API lets you retrieve the wallet balance of addresses on Arweave. The gateway doesn't proxy these requests to nodes.

It would be cool to be able to query balances using the GraphQL API.

I wonder how a trustless implementation of this would work. Performing an aggregation query on the indexed transactions to retrieve a wallet balance might be unscalable.

**Comment by samcamwilliams** [comment]
Hmmm... Proxying to trusted nodes should be fine for this. PRs welcome!

**Comment by CDDelta** [comment]
Proxying would work for trusted peers but I don't believe it would for my use case with non-trusted set-ups. :)

I might have to fallback to the SQL aggregation method for my use case in a fork for now.
