### ISSUE TITLE
Your system of indexing metadata is an antipattern

### ISSUE THREAD

**Issue by vporton** [ArweaveTeam/gateway#91]
You system of creating indices for `INDICES` environment variable is both not enough flexible and over-complicated.

The reasonable way to store metadata is to use a composite PostgreSQL index of both name and value. For queries use JOINs.

Then no need to create a separate DB table field for each index and _every_ index could be used for filtering/sorting.

**Comment by TheLoneRonin** [comment]
@vporton 

Hey VIctor,

First, thank you for taking the time to review everything. Appreciate you taking the time.
Second, agree it was an antipattern.

The intent was to achieve something like this: https://github.com/ArweaveTeam/gateway/issues/6

This will eventually be phased out don't worry.

Thank you for mentioning it (and the other issues).

**Comment by TheLoneRonin** [comment]
Noting that indices should be refactored as part of: #61
